### ISSUE TITLE
Theme demo broken on Hugo Themes Showcase

### ISSUE THREAD

**Issue by onedrawingperday** [tomanistor/osprey#69]
Hello @tomanistor 

Currently your theme's demo does not generate as mentioned in https://github.com/gohugoio/hugoThemes/issues/669#issuecomment-518648215

To fix you need to change [line 8](https://github.com/tomanistor/osprey/blob/master/theme.toml#L8) of `theme.toml` to: `min_version = "0.24.1"`

The `min_version` needs to be a string

Furthermore after testing the above change I noticed the your theme's stylesheet is 404.

In [line 83](https://github.com/tomanistor/osprey/blob/master/layouts/partials/head.html#L83) of `layouts/partials/head.html` you reference a `main.css` file that does not exist in the repo.

Instead under `static/styles/` there is a `main.min.css`

Feel free to close this issue once you do the above

Also note that once gohugoio/hugoThemes#668 is addressed you will need to keep an eye on whether the Osprey theme demo generates on the Hugo website.

We are a very small team and we just cannot keep up opening issues in the various theme repositories. Whenever a theme demo breaks and remains broken then at some point it will be removed from the list without prior warning.

Thank you.

cc: @digitalcraftsman

**Comment by kdevo** [comment]
**Small update:** I could test my changes in PR #70. Seems all good so far.

**Comment by tomanistor** [comment]
Thanks for the alert @onedrawingperday and the fixes @kdevo! I'll have some free time this week to test and merge.

**Comment by ScriptAutomate** [comment]
I should have opened an issue back when I first noticed this issue myself! Thought it was a misconfiguration on my end. I ended up locking my Osprey theme version to a9232a5 when I was first developing with it because of how this broke. If @kdevo 's PR gets merged, I'll definitely be taking a look at upgrading. Love the theme!

**Comment by kdevo** [comment]
Hi again,

after using the theme for quite some time, I implemented some breaking changes to adjust to my requirements.
Because of the nature of my changes (**essentially removing the blog feature**), I forked Osprey, published my changes and voilà, named the child "Osprey Delight".

> :bulb: [Check out the repository here](https://github.com/kdevo/osprey-delight) and please [read the differences](https://github.com/kdevo/osprey-delight#the-taste-features) before you consider a migration. For instance, if you need the blog or dislike other UI changes I made, the original Osprey is still the state of the art!

@tomanistor Hope you're OK with that!
Referring to PR #70 I fixed a small bug for the contact form that came up while developing Osprey Delight. All other parts of Osprey I left untouched in the PR repo so that it can hopefully still be merged without disruptions. Thanks again for the theme!

**Comment by onedrawingperday** [comment]
I have now removed Osprey from the Hugo Themes showcase [as per the guidelines](https://github.com/gohugoio/hugoThemes#theme-maintenance):

>If a theme demo breaks and remains so for more than 30 calendar days, we may remove it from this repository without further notification.

If the above issue is fixed feel free to resubmit the theme at: https://github.com/gohugoio/hugoThemes/issues

**Comment by tomanistor** [comment]
PR #70 has been merged to fix the example site. Thanks guys!
